name: .NET Core Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up .NET Core
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Step 4: Build the application
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Step 5: Run Tests
    - name: Run Tests
      run: dotnet test --configuration Release --no-build

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deploy runs after build and tests are successful

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up .NET Core
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    # Step 3: Publish the application
    - name: Publish Application
      run: dotnet publish --configuration Release --output ./publish

    # Step 4: Deploy (Example: Azure Web App)
    - name: Deploy to Azure Web App
      run: |
        az webapp deploy --name your-webapp-name --resource-group your-resource-group --src-path ./publish
      env:
        AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
