name: .NET Core Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up .NET Core
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Specify .NET 8.0 version

    
    - name: Navigate to Project Directory
      run: cd c:/repo/OrderProcessingApp

   
    - name: Restore dependencies
      run: dotnet restore C:\Users\Admin\source\repos\AssementCoreApplication.csproj

   
    - name: Build
      run: dotnet build C:\Users\Admin\source\repos\AssementCoreApplication.csproj --configuration Release

   
    - name: Run Tests
      run: dotnet test C:\Users\Admin\source\repos\AssementCoreApplication.csproj --configuration Release

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deploy runs after build and tests are successful

    steps:
    # Step 1: Checkout the code again (in case the deploy step needs it)
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up .NET Core (for deployment step)
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    # Step 3: Navigate to the project directory (if needed)
    - name: Navigate to Project Directory
      run: cd c:/repo/OrderProcessingApp

    # Step 4: Publish the app (to a folder for deployment)
    - name: Publish Application
      run: dotnet publish C:\Users\Admin\source\repos\AssementCoreApplication.csproj --configuration Release --output ./publish

    # Step 5: Deploy (Add deployment steps here, depending on your hosting provider)
    - name: Deploy to Hosting Provider
      run: |
        # Example deployment script for deploying to Azure App Service
        # Replace this with your actual deployment steps (Azure, AWS, etc.)
        az webapp deploy --name your-webapp-name --resource-group your-resource-group --src-path ./publish
      env:
        AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
